Refactor all the application to MVVM
AelianaShen/PlantApp pull request #12
Opened 2024-03-27 18:27 UTC by AelianaShen

- Refactor all the app into MVVM structure
- apply [#Preview] in code (https://www.avanderlee.com/xcode/preview-swiftui-uikit-appkit-views/)

2024-03-28 16:54 UTC, wbraynen commented on PlantApp/Components/Plant Card/PlantCardViewModel.swift
> +}
This class doesn't make sense 😅.

2024-03-28 17:16 UTC, wbraynen commented on PlantApp/Components/Plant Card/PlantCard.swift
> +    @ObservedObject var viewModel: PlantCardViewModel
Same here: you are observing an instance of the `PlantCartViewModel` for changes, but the state of that object can never change?  If so, what's the point?

2024-03-28 17:39 UTC, wbraynen commented on PlantApp/Components/Plant Card/PlantCard.swift
> +            viewModel.addToCart(cartManager: cartManager)
Assuming you need a plant card view model at all, why not simply `cartManager.addToCart(product: viewModel.plant)`?  Why is it the view model's job to mutate the cart manager's state?

2024-03-28 17:53 UTC, wbraynen commented on PlantApp/Views/Cart View/CartViewModel.swift
> +class CartViewModel: ObservableObject {
Why is this an observable class and not just a simple struct?

2024-03-28 17:54 UTC, wbraynen commented on PlantApp/Views/Cart View/CartViewModel.swift
> +class CartViewModel: ObservableObject {
Same question about all of your other observables: which ones are necessary and which ones aren't?

2024-03-28 18:01 UTC, wbraynen requested changes
A question about all of the view-model class you have in this PR / in the codebase:

1. When does something need to be observable?  What does observation do?  (You have cases where something that never changes says that it publishes changes.)
2. When you need a view model and when don't you?  (Do you need view models in all your cases.)

Also, enable PR checks to run your unit tests.  Otherwise we have no way of knowing if this PR introduces a regression and risk polluting your `main` branch.

Also, note that your plant images are reloaded/refetched every time.  They should be cached.

2024-03-28 19:43 UTC, wbraynen commented on PlantApp/Views/Cart View/CartViewModel.swift
> +        return "$\(cartManager.total).00"
Don't this by hand.  Use a formatter instead.

https://developer.apple.com/documentation/foundation/numberformatter/style/currency

2024-03-28 19:45 UTC, wbraynen commented on PlantApp/Views/Onboarding View/Getstart View/GetstartView.swift
> +    }
Why is this needed?

2024-03-28 23:50 UTC, wbraynen commented on PlantApp/Components/Answer Row/AnswerRowViewModel.swift
> +    @Published var questionManager: QuestionManager
Here and throughout: Some places you use the older `ObservableObject` with `@Published`, other places you use the newer (iOS 17) `@Observable`.  For example, see your `ScrollSectionViewModel.swift`.  Be consistent.  Pick one and stick with it.  Just keep in mind that, with `@Observable`, any property you don't explicitly mark to not be published will, in fact, be published—properties are published by default there (so an "opt out" model rather than an "opt in").

2024-03-31 16:46 UTC, wbraynen approved these changes
I left some non-blocking comments.  Address them in follow-up PRs.  Let's get this merged in!

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Components/Answer Row/AnswerRowViewModel.swift
> +    let questionManager: QuestionManager
Why is this class observable if nothing can change here?  (`let` means a constant / read only, so cannot mutate.)

Check elsewhere for this too by searching your codebase for `@Observable` and for `ObservableObject`.

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Components/Product Row/ProductRowViewModel.swift
> +        "$\(plant.price)"
Use a formatter.

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Components/Search Bar/SearchBar.swift
> +    @Binding var searchText: String
Does this do anything right now?  You have a ticket to wire it up?  Would it filter what you are already displaying to the user or is this meant to be a server-side search?

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Controllers/CartManager.swift
> +@Observable class CartManager: CartManaging {
Your codebase is still very small.  Soooo, to avoid having N+1 patterns, pick the one you like and just use the same one throughout: either the newer `@Observable` or the older `ObservedObject` with `@Published`.

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Components/Plant Card/PlantCardViewModel.swift
> +        "$\(plant.price)"
Use a formatter.

2024-03-31 16:46 UTC, wbraynen commented on PlantApp/Components/Search Bar/SearchBar.swift
> +        Image(systemName: "mic.fill")
Are you planning to use Siri?  If so, in time for the demo at your defense?  If not, I would remove this for now.

2024-03-31 20:18 UTC, AelianaShen commented on PlantApp/Components/Search Bar/SearchBar.swift
> +    @Binding var searchText: String
[Jira ticket](https://oregonstate-innovationlab.atlassian.net/browse/LAB-583) It filters displaying products in prototype. Haven't completed the development for this feature. :honeybee:

2024-03-31 20:56 UTC, merged