Download a 3D model on demand
AelianaShen/PlantApp pull request #18
Opened 2024-04-06 10:31 UTC by AelianaShen

In the Plant Detail Page, when users click the "AR simulate" button, the program will check whether the plant model exists  the application caches. Then, if not, download it from AWS S3 buckets.

<img width="227" alt="Screenshot 2024-04-06 at 3 29 09 AM" src="https://github.com/AelianaShen/PlantApp/assets/114724075/d2052b5f-b5d6-42a4-8a2e-34ee8d674be8">

2024-04-06 20:27 UTC, wbraynen commented
I tried to run unit tests to see where your code coverage is now with this PR, but your tests are covering more code than you are testing.  It's because of this:
```
@main
struct PlantApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```
When you run the unit-test suite, this gets triggered (because `@main` is entry point into the app code and your tests run the app to test it).  Above you can see it instantiates `ContentView`.  That in turn triggers some other code to run because `ContentView` instantiates some other structs and classes and calls some other functions you wrote.

I gave you some code a while back to fix this, so that your code-coverage report produces a more accurate number.  Add it and include the code-coverage number in your PR's description (and in all subsequent PRs).

2024-04-07 07:21 UTC, wbraynen requested changes
Left some feedback.

Also, I was expecting to see in the video a file downloading and a progress bar showing download progress.  Can you attach a video that shows this?  (That is what this PR implements, right?)

2024-04-07 07:21 UTC, wbraynen commented on PlantApp/NetworkService/UserPreferencesStoreImpl.swift
> +            return nil
Here and elsewhere, this is awkward/nonstandard logic order.  You want instead:

```
guard let careLevelString = userPreferData.string(forKey: "careLevel") else {
   return nil
}

return UserPreferences.CareLevel(rawValue: careLevelString)
```

2024-04-07 07:21 UTC, wbraynen commented on PlantApp/NetworkService/UserPreferencesStoreImpl.swift
`UserPreferences.` appears in the `UserPreferencesStoreImpl` class 16 times.  If you were to namespace `UserPreferencesStoreImpl` under `UserPreferences` (e.g., thus making it `StoreImpl` nested inside a `UserPreferences` extension, as I have suggested in a previous review), you could avoid these 16 mentions.  This would make your code less verbose.

2024-04-07 07:21 UTC, wbraynen commented on PlantApp/Views/AR Place Box View/ARPlaceBoxViewModel.swift
> +    var confirmLuxValue: CGFloat = 0
1. Why is `lightLevel` of type Int and not of type `UserPreferences.LightLevel`?
2. Does the LightLevel enum need a `.none` value?  None of the string enums do—they all get set to `nil`—so why treat integer enums any differently?
3. Why is there a `luxValue` and a `confirmLuxValue`?  Why isn't one enough?

2024-04-07 07:21 UTC, wbraynen commented on PlantApp/Views/AR Place Box View/ARPlaceBoxViewModel.swift
> +    var confirmBoxSize: SIMD3<Float>  = simd_float3(0, 0, 0)
Why `confirmBoxSize`?  `boxSize` above is not enough?

2024-04-07 07:46 UTC, AelianaShen commented on PlantApp/Views/AR Place Plant View/ARPlacePlantViewModel.swift
> +        let downloadURL = URL(string: "https://osu-software-innovation-plants-3d-model.s3.us-west-2.amazonaws.com/\(plant).usdz")!
Yes, you are right. In the POC version, the plant names are unique but not in the future. I'll keep an eye on this and update in the future.

2024-04-07 07:53 UTC, AelianaShen commented on PlantApp/Coordinators/PlacePlantCoordinator.swift
> +        guard let path = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first?.appendingPathComponent("\(name).usdz") else {
Because, in this stage, I want them to be temporary-storage and automatic cleanup by the application. And I don't want the files be backed up to the iCould.

2024-04-07 09:07 UTC, AelianaShen commented on PlantApp/Coordinators/PlacePlantCoordinator.swift
> +        guard let contentsPath = getPathForFile(name: plant) else { return }
Here is the case when the system cannot get the target file path, the one we just moved to from tmp. The handleTap function is been called when I tap on the AR screen to place the plant. I am not sure what is a good way to handle this error. I think the redownload feature is good, but it can be implemented in the ARPlacePlantView, the view that we show the progress bar. We will get an error if the download fails!

2024-04-07 15:30 UTC, wbraynen commented on PlantApp/Coordinators/PlacePlantCoordinator.swift
> +        guard let path = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first?.appendingPathComponent("\(name).usdz") else {
The system can deallocate this anytime though.  You won't get automatic cleanup by the application.  Instead, you will get automatic cleanup by the operating system and it won't necessarily be when it's good for your application or when the user expects it.  If the system runs low on memory, it will delete this file, which in this case seems is not what you want.

What you want is:
1. Not included in iCloud backup.
2. Removed when your app is deleted.
3. Not user facing—the user should not be able to see the file in their Files folders (e.g., My Documents) because, on the phone, this file is only useful to your application and only programmatically.

So, seems what you want is this combination:
![image](https://github.com/AelianaShen/PlantApp/assets/4765449/6f5aa150-65e2-4183-b440-eacf2b4316ba)

Apple's documentation:
https://developer.apple.com/documentation/foundation/url/3988452-applicationsupportdirectory
https://developer.apple.com/documentation/foundation/nsurlisexcludedfrombackupkey

You can ask GPT 4 "How to set NSURLIsExcludedFromBackupKey on a file?" and it should be able to help you.

2024-04-07 15:42 UTC, wbraynen commented on PlantApp/Views/AR Place Plant View/ARPlacePlantViewModel.swift
> +        let downloadURL = URL(string: "https://osu-software-innovation-plants-3d-model.s3.us-west-2.amazonaws.com/\(plant).usdz")!
Why not just rename them to use plant ID numbers instead?  That would be industry standard (exactly because it's a unique identifier).

2024-04-07 17:05 UTC, AelianaShen commented on PlantApp/Views/AR Place Plant View/ARPlacePlantViewModel.swift
> +        let downloadURL = URL(string: "https://osu-software-innovation-plants-3d-model.s3.us-west-2.amazonaws.com/\(plant).usdz")!
Yeah, I agree with your point! Just, that means I need to update 10 plant products name in the s3 bucket to get the new public path. I am just thinking that will be a bit inconvenient for me to find a particular plant from the bucket list if in case I need to fix a plant file. 😬

<img width="1321" alt="Screenshot 2024-04-07 at 9 54 29 AM" src="https://github.com/AelianaShen/PlantApp/assets/114724075/29b4194e-a280-4b73-849f-8dfcc7b2db48">

2024-04-07 17:27 UTC, wbraynen approved these changes
Approving to not block you.  Keep moving.

2024-04-07 17:30 UTC, AelianaShen commented on PlantApp/Views/AR Place Box View/ARPlaceBoxViewModel.swift
> +    var confirmLuxValue: CGFloat = 0
1. solved in e00b898
2. Yeah, that's weird that it's not set to nil. I am thinking about how to assign nil to LightLevel, cause I thought it is possible to write like the image below, just like the other program language, but actually it can't.
<img width="949" alt="Screenshot 2024-04-07 at 10 24 41 AM" src="https://github.com/AelianaShen/PlantApp/assets/114724075/002ec339-28be-455a-967c-4c9bf9bedb22">

2024-04-10 20:41 UTC, merged