add placing 3D plant feature
AelianaShen/PlantApp pull request #8
Opened 2024-03-08 23:57 UTC by AelianaShen

2024-03-09 05:07 UTC, wbraynen commented
@AelianaShen I don't know how to review this.  There is nothing in your PR description and no link to a ticket.  What's the AC for this?  I could try to review the code blindly, but what am I supposed to be testing and what's this PR supposed to accomplish?

2024-03-11 18:28 UTC, AelianaShen commented
> @AelianaShen I don't know how to review this. There is nothing in your PR description and no link to a ticket. What's the AC for this? I could try to review the code blindly, but what am I supposed to be testing and what's this PR supposed to accomplish?

Hi Prof. Will,
Sorry about the mistake. The description has been updated and I also linked to a Jira ticket!

2024-03-12 14:55 UTC, wbraynen requested changes
I requested some code comments.  Unfortunately I do not have time to QA this, so, since looks like it's a feature implementation, you'll want to request a review from someone who can QA your work here as you have described in your PR description.  Another option is to have someone QA directly off main, which would help you merge this PR quicker.  Let me know which you prefer.

2024-03-12 14:55 UTC, wbraynen commented on PlantApp/Views/ViewContainers/ARPlacePlantViewContainer.swift
> +    }
`makeCoordinator` isn't called from anywhere.  So, someone else reading this code might think this was left here by mistake.  Maybe add a docstring explaining that you are implementing `https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable/makecoordinator()-32trb` and why?

Same elsewhere where you implement `makeCoordinator`.

2024-03-12 14:55 UTC, wbraynen commented on PlantApp/Models/PlantModel.swift
>          description: "Mini Fiddle-Leaf Fig or scientifically known as Ficus lyrata 'Bambino,' is a smaller and more compact version of the popular Fiddle-Leaf Fig (Ficus lyrata).",
Can you localize this and other text into at least one other language?  Once you localize it, you will understand why we are not fetching this text from the server (as I think you tried to do earlier).

Localization can be a different ticket, so non-blocking for this PR.

2024-03-12 17:38 UTC, AelianaShen commented on PlantApp/Coordinators/PlacePlantCoordinator.swift
> +        let modelEntity = try! Entity.loadModel(named: modelName + ".usdz")
Sounds good! I simply print the message "Failed to load model: \(modelName)" to implement minimal error handling here.

2024-03-12 17:56 UTC, AelianaShen commented on PlantApp/Views/ViewContainers/ARPlacePlantViewContainer.swift
> +    }
I believe makeCoordinator was called during the life cycle in `ARPlacePlantViewContainer`. But it's hard for me, this noob, to explain.😳 So, I ask ChatGPT to help me to explain here:

> The `PlacePlantCoordinator` function will be called when the `ARPlacePlantViewContainer` view is created. Let's break down the process:
> 
> 1. When you create an instance of `ARPlacePlantViewContainer`, the `init(plant:)` initializer is called. This initializer sets up the initial state of the `ARPlacePlantViewContainer`, including storing the plant name.
> 
> 2. When SwiftUI needs to create the underlying `UIView` representation of `ARPlacePlantViewContainer`, it calls the `makeUIView(context:)` method. Inside this method:
>    - An `ARView` is created and configured for AR functionality.
>    - A tap gesture recognizer is created and added to the `ARView`.
>    - The `makeCoordinator()` method is called to create an instance of `PlacePlantCoordinator`.
>    - The coordinator's `arView` property is set to the `ARView`.
> 
> 3. The `makeCoordinator()` method creates and returns an instance of `PlacePlantCoordinator`, passing the plant name to its initializer.
> 
> 4. The `handleTap` method of the `PlacePlantCoordinator` instance is set as the action for the tap gesture recognizer.
> 
> 5. The coordinator instance is assigned as the target of the tap gesture recognizer.
> 
> So, in summary, the `PlacePlantCoordinator` function is called when `makeCoordinator()` is invoked during the creation of the `ARPlacePlantViewContainer`. The purpose of `PlacePlantCoordinator` is to handle tap gestures and coordinate actions related to placing plants in the AR scene.
>

2024-03-12 18:44 UTC, AelianaShen commented
> I requested some code comments. Unfortunately I do not have time to QA this, so, since looks like it's a feature implementation, you'll want to request a review from someone who can QA your work here as you have described in your PR description. Another option is to have someone QA directly off main, which would help you merge this PR quicker. Let me know which you prefer.

 I prefer to merge first, then invite Radhika to QA the main, if she is willing to help. 🌞

2024-03-12 19:22 UTC, wbraynen commented on PlantApp/Views/ViewContainers/ARPlacePlantViewContainer.swift
> +    }
Not sure this helps.  It's a mouthful.  You want to make sure that (a) you understand it yourself and (b) it's more succinct—you just need a sentence or two.

2024-03-12 19:25 UTC, wbraynen commented
> > I requested some code comments. Unfortunately I do not have time to QA this, so, since looks like it's a feature implementation, you'll want to request a review from someone who can QA your work here as you have described in your PR description. Another option is to have someone QA directly off main, which would help you merge this PR quicker. Let me know which you prefer.
> 
> I prefer to merge first, then invite Radhika to QA the main, if she is willing to help. 🌞

Also, doesn't have to be Radhika.  You can ask anyone for help, including anyone in the lab but can also be someone else you know.

2024-03-12 19:30 UTC, wbraynen commented on PlantApp/Coordinators/PlacePlantCoordinator.swift
> +        let modelEntity = try! Entity.loadModel(named: modelName + ".usdz")
I mean, that's no error handling at all I think.  You are logging to a console where no one will see it.  But you can think about this later and not high priority.

2024-03-12 19:31 UTC, wbraynen approved these changes
Some nitpicks, nothing blocking.  Approving.

2024-03-12 19:59 UTC, merged